/// Sanity tests for NullVote election + Groth16 integration.
///
/// The main thing we validate here is that the snarkjs → arkworks byte
/// conversion pipeline produces bytes that `sui::groth16::verify_groth16_proof`
/// accepts. End-to-end flow (create → finalize → cast → double-vote → tally)
/// is exercised via the CLI scripts in `scripts/deploy.sh` because reproducing
/// specific shared-object IDs inside `sui move test` requires byte-level
/// scenario patching that isn't worth the time cost for a hackathon.
#[test_only]
module nullvote::election_tests {
    use sui::groth16;
    use nullvote::vk;

    /// Sample proof + public inputs generated by
    ///   bash circuits/scripts/compile.sh && bash circuits/scripts/setup.sh &&
    ///   node circuits/scripts/gen_sample_input.js &&
    ///   npx snarkjs groth16 fullprove inputs/sample_input.json \
    ///     build/vote_js/vote.wasm build/vote_final.zkey \
    ///     build/proof.json build/public.json &&
    ///   ./circuits/scripts/export_vk_rs/target/release/nullvote-export-vk circuits/build
    ///
    /// Regenerate along with `nullvote::vk` if the circuit or setup changes.
    const SAMPLE_PROOF: vector<u8> = x"940be05e3cf677bc9e0bdc1622292546e43f690d8cd48f6cf9f27eb4fcb122afdb611b1efdd9326f36d38c5e3695587664a5170d8546adc1a9b6b10772cd0c1b301dc75b62991be83c8fe5e6ace1e462c7ae9a982f569e69ac6450f2043045896fc22087800a6369594116ec687330ccdf9bcf8773a7cc1ca4dc5567a65cce2e";
    const SAMPLE_PUBLIC: vector<u8> = x"f61c85b11fab4474dcf9c2a40e10d9aec9a3ee63c0e2738b55ca6ba19bc7891a5e4f7eb41f38a82b86a4bfb5db900bcf316df598367aa3f684abdd685c0e1a2befcdab907856341200000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000";

    #[test]
    fun verify_groth16_happy_path() {
        let curve = groth16::bn254();
        let vk_bytes = vk::bytes();
        let pvk = groth16::prepare_verifying_key(&curve, &vk_bytes);
        let pi = groth16::public_proof_inputs_from_bytes(SAMPLE_PUBLIC);
        let proof = groth16::proof_points_from_bytes(SAMPLE_PROOF);
        assert!(groth16::verify_groth16_proof(&curve, &pvk, &pi, &proof), 0);
    }

    #[test]
    fun verify_groth16_rejects_tampered_public_input() {
        let mut tampered = SAMPLE_PUBLIC;
        // Flip the LSB of the first byte of the `vote_public` field (offset 96).
        let b = vector::borrow_mut(&mut tampered, 96);
        *b = *b ^ 0x01;

        let curve = groth16::bn254();
        let vk_bytes = vk::bytes();
        let pvk = groth16::prepare_verifying_key(&curve, &vk_bytes);
        let pi = groth16::public_proof_inputs_from_bytes(tampered);
        let proof = groth16::proof_points_from_bytes(SAMPLE_PROOF);
        assert!(!groth16::verify_groth16_proof(&curve, &pvk, &pi, &proof), 0);
    }

    #[test]
    fun verify_groth16_rejects_tampered_proof() {
        let mut tampered = SAMPLE_PROOF;
        let b = vector::borrow_mut(&mut tampered, 0);
        *b = *b ^ 0x01;

        let curve = groth16::bn254();
        let vk_bytes = vk::bytes();
        let pvk = groth16::prepare_verifying_key(&curve, &vk_bytes);
        let pi = groth16::public_proof_inputs_from_bytes(SAMPLE_PUBLIC);
        // Corrupting the first byte of the compressed A point often yields an
        // invalid encoding that aborts before pairing — we only assert "not
        // accepted" which covers both false-return and abort paths at the test
        // boundary. If deserialization aborts here, the function never returns
        // so this test will fail; in that case swap the tampered offset to a
        // valid-curve-point-but-wrong-value (e.g. mutate byte 64 of pi_b).
        let proof = groth16::proof_points_from_bytes(tampered);
        assert!(!groth16::verify_groth16_proof(&curve, &pvk, &pi, &proof), 0);
    }
}
