/// Sanity tests for NullVote election + Groth16 integration.
///
/// The main thing we validate here is that the snarkjs → arkworks byte
/// conversion pipeline produces bytes that `sui::groth16::verify_groth16_proof`
/// accepts. End-to-end flow (create → finalize → cast → double-vote → tally)
/// is exercised via the CLI scripts in `scripts/deploy.sh` because reproducing
/// specific shared-object IDs inside `sui move test` requires byte-level
/// scenario patching that isn't worth the time cost for a hackathon.
#[test_only]
module nullvote::election_tests {
    use sui::groth16;
    use nullvote::vk;

    /// Sample proof + public inputs generated by
    ///   bash circuits/scripts/compile.sh && bash circuits/scripts/setup.sh &&
    ///   node circuits/scripts/gen_sample_input.js &&
    ///   npx snarkjs groth16 fullprove inputs/sample_input.json \
    ///     build/vote_js/vote.wasm build/vote_final.zkey \
    ///     build/proof.json build/public.json &&
    ///   ./circuits/scripts/export_vk_rs/target/release/nullvote-export-vk circuits/build
    ///
    /// Regenerate along with `nullvote::vk` if the circuit or setup changes.
    const SAMPLE_PROOF: vector<u8> = x"817908e7d607da5acb94b0894437b53731430ce4e8aa86ce715f0c754489059b75a0879f65c3df95b924cda8608da91c39738a0b74b9a04c86521776ee7b25128929e8d6988f8d35a26d5d61243ac569a360e7f59ed950822ec5a307225a25a6a3b8771d1e6dc8c00352ec7cb65706baf1fde19eb263547dfa354319102e328f";
    const SAMPLE_PUBLIC: vector<u8> = x"9ce1f5aeb9d69daac639fca65e327996b4c554c9bef893ccf125e6ee625a4500034a78e9ca3e007b83101bd94c4f413bc43d19393500f723c97b6256b28e230befcdab907856341200000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000";

    #[test]
    fun verify_groth16_happy_path() {
        let curve = groth16::bn254();
        let vk_bytes = vk::bytes();
        let pvk = groth16::prepare_verifying_key(&curve, &vk_bytes);
        let pi = groth16::public_proof_inputs_from_bytes(SAMPLE_PUBLIC);
        let proof = groth16::proof_points_from_bytes(SAMPLE_PROOF);
        assert!(groth16::verify_groth16_proof(&curve, &pvk, &pi, &proof), 0);
    }

    #[test]
    fun verify_groth16_rejects_tampered_public_input() {
        let mut tampered = SAMPLE_PUBLIC;
        // Flip the LSB of the first byte of the `vote_public` field (offset 96).
        let b = vector::borrow_mut(&mut tampered, 96);
        *b = *b ^ 0x01;

        let curve = groth16::bn254();
        let vk_bytes = vk::bytes();
        let pvk = groth16::prepare_verifying_key(&curve, &vk_bytes);
        let pi = groth16::public_proof_inputs_from_bytes(tampered);
        let proof = groth16::proof_points_from_bytes(SAMPLE_PROOF);
        assert!(!groth16::verify_groth16_proof(&curve, &pvk, &pi, &proof), 0);
    }

    #[test]
    fun verify_groth16_rejects_tampered_proof() {
        let mut tampered = SAMPLE_PROOF;
        let b = vector::borrow_mut(&mut tampered, 0);
        *b = *b ^ 0x01;

        let curve = groth16::bn254();
        let vk_bytes = vk::bytes();
        let pvk = groth16::prepare_verifying_key(&curve, &vk_bytes);
        let pi = groth16::public_proof_inputs_from_bytes(SAMPLE_PUBLIC);
        // Corrupting the first byte of the compressed A point often yields an
        // invalid encoding that aborts before pairing — we only assert "not
        // accepted" which covers both false-return and abort paths at the test
        // boundary. If deserialization aborts here, the function never returns
        // so this test will fail; in that case swap the tampered offset to a
        // valid-curve-point-but-wrong-value (e.g. mutate byte 64 of pi_b).
        let proof = groth16::proof_points_from_bytes(tampered);
        assert!(!groth16::verify_groth16_proof(&curve, &pvk, &pi, &proof), 0);
    }
}
